In [1]:
import array

In [2]:
from array import *

In [3]:
vals = array('i',[5,9,-8,4,2])
vals

array('i', [5, 9, -8, 4, 2])

In [4]:
vals.buffer_info() #address, size

(1691935195024, 5)

In [5]:
vals.typecode

'i'

In [6]:
vals.reverse()

In [7]:
vals[0]

2

In [8]:
vals

array('i', [2, 4, -8, 9, 5])

In [9]:
for i in range (5):
    print(vals[i])

2
4
-8
9
5


In [10]:
for i in range (len(vals)):
    print(vals[i])

2
4
-8
9
5


In [11]:
for i in vals:
    print(i)

2
4
-8
9
5


In [12]:
values = array('u',['a','e','i','o','u'])
values

array('u', 'aeiou')

In [13]:
for i in values:
    print(i)

a
e
i
o
u


In [14]:
newArr = array(vals.typecode, (a for a in vals))

In [15]:
for i in newArr:
    print(i)

2
4
-8
9
5


In [16]:
newArr1 = array(vals.typecode, (a*a for a in vals))

In [17]:
for i in newArr1:
    print(i)

4
16
64
81
25


In [18]:
i=0
while i<len(newArr):
    print(newArr[i])
    i+=1

2
4
-8
9
5


- How to create an empty array?
- How to create an array through user input?
- Array creation by taking the values from a user
- How to search an element in an array?
- Function used to get the index value of an element in python

#1
- We can also create a blank array and can take the values for it from the user.
- First, we have to take the length of an array from the user. 
- input() function takes the value in the form of a string, so we have to change it into an integer using int().
- We can run a loop in a range of length of an array given by the user. At each iteration, we can take a value to be inserted in an array.
- append() is a function that is used to add a value or an element in an array.

#2
- To search for any value in an array or to check the index number at which the value is present, we need to increment the value of an iterator variable in every iteration.
- When the condition of comparison gets true, we stop the loop to iterate further and print the value of an iterator variable.
- The iterator variable will return an index number of the value, you have searched for.

#3
- index() function can also be used to get the index number of a value in an array.

In [19]:
arr = array('i',[])
n = int(input('Range of Array: '))

for i in range (n):
    x=int(input('Array Value: '))
    arr.append(x)
    
print(arr)    

Range of Array: 3
Array Value: 1
Array Value: 2
Array Value: 3
array('i', [1, 2, 3])


In [20]:
val = int(input('Enter search value: '))
k=0
for e in arr:
    if e== val:
        print(k)
        break
    k+=1    

Enter search value: 3
2


In [21]:
val = int(input('Enter search value: '))

print(arr.index(val))

Enter search value: 1
0


In [22]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [23]:
import numpy as np

In [4]:
from numpy import *

In [25]:
arr=array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


-- Ways of creating arrays in numpy: 
   we have 6 way of creating arrays in numpy
    a)array()
    b)linspace()
    c)arange()
    d)logspace()
    e)zeros()
    f)ones()

from numpy import * 
arr =array([1,2,3,4,5])
print(arr) 
print(arr.dtype) # int32

arr =array([1,2,3,4,5.0])
print(arr.dtype) # float
-- automatically it will convert the data type to float

arr =array([1,2,3,4,5],float)
print(arr.dtype) # float 
-- we can also specify the data type of array 

b) linspace() 
-- it is used to create an array with equal interval between the elements 
-- syntax: linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None)
arr=linspace(0,15,16) # here it break the range into 16 equal parts 
-- by default it will take 50 parts 

arr =linspace(0,15)
print(arr)

c) arange()
-- it is used to create an array with equal interval between the elements
-- syntax: arange(start,stop,step,dtype=None) 
arr =arange(1,15,2)
print(arr) 
-- it will create an array with start value 1 and end value 15 with step size 2
arr=arange(1,15,2.5)

d) logspace()
-- it is used to create an array with equal interval between the elements in log scale
-- syntax: logspace(start,stop,num=50,endpoint=True,base=10.0,dtype=None) 
arr=logspace(1,40,5)
print(arr) 

e) zeros()
-- it is used to create an array with all zeros 
-- syntax: zeros(shape,dtype=float,order='C') 
arr= zeros(5)
print(arr)


f) ones()
-- it is used to create an array with all ones 
-- syntax: ones(shape,dtype=float,order='C')
arr=ones(5)
print(arr)

--if i want work with int
arr=ones(4,int)
print(arr)


In [26]:
arr=array([1,2,3,4,5,6],float)
print(arr)

[1. 2. 3. 4. 5. 6.]


In [27]:
arr.dtype

dtype('float64')

- Addition of values in an array
- Different functions that can be performed on arrays
- What is Aliasing in python?
- Different ways of copying an array


#1
- We can add any value in each element of an array.
- We can also add values of two arrays. 
- The addition of two arrays is known as Vectorized Operation.
- We can also find the values of each element of an array of mathematical operations such as sin, cos, tan, log, sqrt etc.
- Sum of every element of an array can also be calculated by using the sum() function.
- Minimum value can also be get from an array through the min() function.
- Maximum value can be get from an array by using the max() function.
- Unique elements from an array and the sorted array can also be get.
- Concatenation of two arrays can also be performed by using the concatenate function. This function combines two arrays.

#2
- Two variables can be pointed towards a single array. It means both variables are pointing to the same memory address where the array is stored.
- In Python, Aliasing happens whenever one variable's value is assigned to another variable.
- view() is a function that helps to create a new array at a new location. It means arrays should be present at the different memory addresses.
- By using the view() functions, two variables will point towards two different arrays.

#3
- In python, two copying techniques are available i.e.,
1. Shallow Copy
2. Deep Copy
- In shallow copy, it will copy elements but it means both arrays are dependent on each other.
- In shallow copy, if we update an element in one array then the changes would also be reflected in another array.
- In a deep copy, two different arrays are not linked with each other in any way.
- In a deep copy, we use the function known as a copy() instead of using the view() function.
- copy() function provides a deep copy of an array.

In [28]:
arr=array([1,2,3,4,5,6])
arr = arr+5
print(arr)

[ 6  7  8  9 10 11]


In [29]:
arr=array([1,2,3,4,5,6])
arr1=array([7,8,9,10,11,12])
arr2=arr+arr1
arr2

array([ 8, 10, 12, 14, 16, 18])

In [30]:
sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [31]:
min(arr)

1

In [32]:
max(arr)

6

In [33]:
concatenate([arr,arr1])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
print(arr)

[1 2 3 4 5 6]


## Multi-Dimensional Arrays

- Two-dimensional array in Python
- Attributes available with a two-dimensional array
- How to convert the dimensions of an array
- Matrix in Python
- How to convert an array into a matrix?
- Functions used with a matrix


#1
- If a list contains multiple elements of the same type, then it is known as an array.
- When an array contains another array inside it, then it is known as a two-dimensional array.
- Two- dimensional array can be defined as an array within another array. 
- It is a collection of rows and columns.

Syntax of a two-dimensional array:-
arr= array([
   [arr1],
   [arr2]
  ])

#2
Attributes with two-dimensional arrays:-
- dtype attribute returns the data type of the data with which you are working.
- ndim attribute gives the number of dimensions of an array and also gives the rank to an array.
e.g, if it is a single-dimensional array then it will return 1 if three-dimensional array then it returns 3.
It will also give the rank whether it is 1-D, 2-D and many more.
- shape attribute returns the number of rows and the number of columns present inside an array.
- size attribute gives the size of the entire block.
- flatten attribute convert the 2-dimensional array into a single-dimensional array.

#3
- reshape attribute is used to change the dimensions of an array. We can convert a 1-D array to a 2-D array by using the reshape method.
- reshape(r,c) method takes two parameters ie., the number of rows and a number of columns, that you want in an updated array.
-  reshape attribute also works with a 3-D array. In 3-D, we have multiple 2-D arrays. And a 2-D array contains multiple 1-D arrays.

#4
- Matrices can be defined as a two-dimensional array that has multiple rows and columns.
- A matrix that has one row and multiple columns is known as a row matrix.
-  A matrix having one column and multiple rows is known as a column matrix.
- Both the row matrix and column matrix is in the form of a single-dimensional array.
- A separate format available for a matrix in python.

#5
Functions with matrix:-
- matix() attribute is used to convert an array into a matrix format.
- We can also create a matrix without using an array. It can also be created directly by using the matrix() attribute.
 matrix('1 2  3 6 ; 4 5 6 7')
In this, values are separated by using the space, and rows are separated by using the semicolon.
- A diagonal () function can be used to only print the diagonal elements of an array.
- min() function will give the minimum value element from an array.
- max() function is used to get the maximum value element of an array.
- There is a certain number of rules that should be followed in matrix multiplication.


In [37]:
arr1=array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [38]:
print(arr1.ndim)

2


In [40]:
arr2 = array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
arr2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
arr2.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arr2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [43]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [46]:
m=matrix(arr1)
print(m)

[[1 2 3]
 [4 5 6]]


In [53]:
m1 = matrix('1 2; 3 4; 5 6; 7 8; 9 10')
print(m1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [49]:
print(diagonal(m1))

[1 4]


In [51]:
print(m1.min())

1


In [7]:
m2 = matrix('1 2 3; 4 5 6; 7 8 9')
m3 = matrix('11 12 13; 14 15 16; 17 18 19')
m4 = m2*m3;
print(m4)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
