In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
a[0]

1

In [6]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [7]:
a1-a2

array([-3, -3, -3])

In [8]:
a1*a2

array([ 4, 10, 18])

In [9]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [14]:
a = np.array([5,6,9])
a

array([5, 6, 9])

In [15]:
a.ndim

1

In [16]:
a[1]

6

In [17]:
a=np.array([[1,2],[3,4],[5,6]])
a.ndim #no. of dimensions

2

In [18]:
a.itemsize #byte size of each element. integer=4

4

In [19]:
a.dtype

dtype('int32')

In [20]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.float)
a.dtype

C:\Users\Mroads\AppData\Local\Temp\ipykernel_19284\1189558954.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array([[1,2],[3,4],[5,6]], dtype=np.float)


dtype('float64')

In [21]:
a.itemsize

8

In [22]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [23]:
a.size #total no. of elements

6

In [24]:
a.shape #rows,col

(3, 2)

In [25]:
a=np.array([[1,2],[3,4],[5,6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [26]:
#initialize array with all zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
l=range(5)
l

range(0, 5)

In [29]:
l[2]

2

In [31]:
np.arange(1,5)

array([1, 2, 3, 4])

In [32]:
np.arange(1,5,2) #every second number

array([1, 3])

In [33]:
np.linspace(1,5,10) #linearly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [34]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [35]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
a.shape

(3, 2)

In [37]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a.ravel() #flatten array, but will not touch the original array

array([1, 2, 3, 4, 5, 6])

In [39]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
a.min()

1

In [43]:
a.max()

6

In [44]:
a.sum()

21

In [46]:
a.sum(axis=0) #axis=0 -> column or y axis; axis=1 -> row or x axis

array([ 9, 12])

In [47]:
a.sum(axis=1)

array([ 3,  7, 11])

In [49]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [50]:
np.std(a)

1.707825127659933

In [51]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [52]:
a

array([[1, 2],
       [3, 4]])

In [53]:
b

array([[5, 6],
       [7, 8]])

In [54]:
a+b

array([[ 6,  8],
       [10, 12]])

In [55]:
a-b

array([[-4, -4],
       [-4, -4]])

In [56]:
a*b

array([[ 5, 12],
       [21, 32]])

In [57]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [58]:
a.dot(b) #matrix product

array([[19, 22],
       [43, 50]])

In [59]:
n=[6,7,8]

In [60]:
n[0:2] #will not print nth no.

[6, 7]

In [61]:
n[-1]

8

In [62]:
a=np.array([6,7,8])

In [63]:
a[0:2]

array([6, 7])

In [64]:
a[-1]

8

In [65]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [66]:
a[1,2] #row 1, column 2

3

In [68]:
a[0:2,2] #rows 0,1, column 2

array([8, 3])

In [69]:
a[-1]

array([9, 3, 2])

In [70]:
a[-1,0:2]

array([9, 3])

In [71]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [72]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [73]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [74]:
#flatten
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [76]:
#stacking
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [77]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [78]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [79]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [80]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [81]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [83]:
result = np.hsplit(a,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [84]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [85]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [86]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [88]:
result = np.vsplit(a,2)
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [89]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [90]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [93]:
#indexing with boolean arrays
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [95]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [96]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [97]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]], np.int32)
np.savetxt("test.txt",x)

In [99]:
#y = np.loadtxt("text.txt")
#print(y)

In [102]:
a=np.arange(12).reshape(3,4)

In [104]:
#row wise right to left
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [103]:
#Fortran Order, column wise top to botton
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [106]:
for x in np.nditer(a,order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [107]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...] = x*x

In [108]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [105]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [110]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
